In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [ ]:
print("pytorch")

pytorch


In [ ]:
!nvidia-smi # to cheack gpu version

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
# introduction to Tensor

## creating the tensor 

# pytorch ternsor is created using the torch.tensor()

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # dimension (pair of the closing sq baraket )

0

In [ ]:
scalar.item() #get tensor back as python int

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX=torch.tensor([[2,3],
                     [3,4]])
MATRIX

tensor([[2, 3],
        [3, 4]])

In [ ]:
MATRIX[0]


tensor([2, 3])

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [2,4,5],
                      [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 4, 5],
        [5, 6, 7]])

random tensor

In [ ]:
#creating the random tensor of size (9,4)
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[0.0298, 0.7332, 0.9518, 0.1373],
        [0.1649, 0.2093, 0.4030, 0.9485],
        [0.7896, 0.7622, 0.8225, 0.6004]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#creating the random tensor of size 
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.3581, 0.2966, 0.6863, 0.3259],
         [0.4214, 0.9814, 0.5580, 0.8863],
         [0.0419, 0.2627, 0.5692, 0.0446]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4763, 0.4572, 0.3635, 0.0855],
        [0.9992, 0.9800, 0.3209, 0.5444],
        [0.1388, 0.7446, 0.3877, 0.8686]])

In [ ]:
#creating a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))# height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

zeros and ones


In [ ]:
#creatiung the tensor  of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creating the  tensor of all ones

ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

Creating a range of tensors and tensors-like


In [ ]:
# use torch.arange()
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
number=torch.arange(start=1,end=1000,step=33)
number

tensor([  1,  34,  67, 100, 133, 166, 199, 232, 265, 298, 331, 364, 397, 430,
        463, 496, 529, 562, 595, 628, 661, 694, 727, 760, 793, 826, 859, 892,
        925, 958, 991])

In [ ]:
# creating tensor like
the_zeros=torch.zeros_like(input=number)
the_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0])

Tensor datatype


tensor datatype is one of the 3 big error u will run with pytorch and deep learing

1.tensor is not a right datatype
2.tensor not right shape
3.tensor not on the right device



In [ ]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,4.0,7.0],
                            dtype=None )
float_32_tensor


tensor([3., 4., 7.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=torch.tensor([3.0,4.0,7.0],
                            dtype=torch.float16 )
float_16_tensor


tensor([3., 4., 7.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor=torch.tensor([3.0,4.0,7.0],
                            dtype=None,#datatype of tensor
                             device=None,#device is ur tensor on
                            requires_grad=False)#whether or not gradients with this tensor operation
float_32_tensor


tensor([3., 4., 7.])

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 7.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 49.])

In [ ]:
int_32_tensor=torch.tensor([2,4,5],dtype=torch.int32)
int_32_tensor

tensor([2, 4, 5], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 6., 16., 35.])

In [ ]:
int_64_tensor=torch.tensor([2,4,5],dtype=torch.int64)
int_64_tensor

tensor([2, 4, 5])

In [ ]:
float_32_tensor*int_64_tensor

tensor([ 6., 16., 35.])

In [ ]:
int_long_tensor=torch.tensor([2,4,5],dtype=torch.long)
int_long_tensor

tensor([2, 4, 5])

In [ ]:
float_32_tensor*int_long_tensor

tensor([ 6., 16., 35.])

getting the information from tensor (tensor attributes)

1.tensor not right datatype-tensor.dtype

2.tensor not right shape-tensor.shape

3 tensor not on the right device-tensor.device



In [ ]:
#creating the tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5081, 0.0421, 0.9228, 0.9778],
        [0.3125, 0.2568, 0.3084, 0.8525],
        [0.2494, 0.6900, 0.3985, 0.3319]])

In [ ]:
some_tensor.size(),some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
#find out details about some tensor 

print(some_tensor)
print(f"datatype of tensor:{some_tensor.dtype}")
print(f"shape of the tensor:{some_tensor.shape}")
print(f"device tensor is on:{some_tensor.device}")

tensor([[0.5081, 0.0421, 0.9228, 0.9778],
        [0.3125, 0.2568, 0.3084, 0.8525],
        [0.2494, 0.6900, 0.3985, 0.3319]])
datatype of tensor:torch.float32
shape of the tensor:torch.Size([3, 4])
device tensor is on:cpu


manipulating the tensor(tensor operation

1.addition

2.sub

3.mull

4.division

5.matrix mull



In [ ]:
#creating the tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#mull
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-2#sub

tensor([-1,  0,  1])

In [ ]:
# pytorch built-in
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

matrix mull(dot product)

1.element wise multiplication

2.matrix multiplication(dot product)

***two main rules for matrix mull :-

1.**inner dimension** must match

'(3,2)@(3,2) 'wont works

(2,4)@(4,2) works

(7,8)@(8,7) works

2.resulting matrix has the shape of the **outer dimension**

'(3,4)@(4,5)'-->(3,5)

'(8,3)@(3,5)'-->(8,5)








In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,4))

tensor([[0.5686, 0.5035, 0.4582, 0.3071],
        [0.9778, 0.8428, 0.8013, 0.5116],
        [1.2017, 0.9202, 1.0527, 0.5455]])

In [ ]:
print(tensor,"*",tensor)
print(f"equalsL:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equalsL:tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.66 ms, sys: 532 µs, total: 3.19 ms
Wall time: 3.21 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 374 µs, sys: 51 µs, total: 425 µs
Wall time: 319 µs


tensor(14)

In [ ]:
#one common mistake :shape error in matrix mull
tensor_a=torch.tensor([[1,2],
           [3,4],
           [5,6]])
tensor_b=torch.tensor([[2,4],
          [4,6],
          [9,39]])

In [ ]:
torch.mm(tensor_a, tensor_b) # matmul-->mm are same

RuntimeError: ignored

In [ ]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
#to fix the tensor  shape issuse ,we can manipulate the shape of one of our  tensor using the transpose

# transpose-->switches the axes or dimension of the given tensor



In [ ]:
tensor_b.shape

torch.Size([3, 2])

In [ ]:
tensor_b.T,tensor_b.shape

(tensor([[ 2,  4,  9],
         [ 4,  6, 39]]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 10,  16,  87],
        [ 22,  36, 183],
        [ 34,  56, 279]])

In [ ]:
 # The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_a.shape}, tensor_B = {tensor_b.shape}\n")
print(f"New shapes: tensor_A = {tensor_a.shape} (same as above), tensor_B.T = {tensor_b.T.shape}\n")
print(f"Multiplying: {tensor_a.shape} * {tensor_b.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_a, tensor_b.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 10,  16,  87],
        [ 22,  36, 183],
        [ 34,  56, 279]])

Output shape: torch.Size([3, 3])


finding the min max mean sum,etc(tensor aggregation)




In [ ]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#find the min


torch.min(x),x.min()


(tensor(0), tensor(0))

In [ ]:
#find the max

torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean -note:torch.mean() funtion requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x)

tensor(450)

finding the position min and max






In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin() # argmin -> return index position of target tensor that has minmum value with argmamax()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

1.**Reshape**-reshape an input tensor to  defind shape

2.**viem**-return a view of an input tensor of certain shape but keep the same memory as the original tensor

3.**squeeze**-remove all the 1 dimension in tensor 

4.**stacking**-combine all the tensor on top of each other(vstack) or side by side (hstack)

5.**Unsqueeze**-add 1 dimension to the target tensor

6.**Permute**-return a view of the input with dimension permuted(swapped)in certain way
 


In [ ]:
#let create a tensor
import torch 
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z=x.view(1,9)
z,z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0]=5 #changing the z changes the x (bez a view of tensor shares the same memory as the original input)
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensor on top of the each other

x_stacked=torch.stack([x,x,x,x],dim=0) # vstack
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked #h stack


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
print(f"previous tensor:{x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# remove extra dimension from the x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f" new_tensor:{x_squeezed}")
print(f"new_shape:{x_squeezed.shape}")

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])
 new_tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new_shape:torch.Size([9])


In [ ]:
print(f" new_tensor:{x_squeezed}")
print(f"new_shape:{x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0) # v 
print(f" new_tensor:{x_unsqueezed}")
print(f"new_shape:{x_unsqueezed.shape}")

 new_tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new_shape:torch.Size([9])
 new_tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new_shape:torch.Size([1, 9])


In [ ]:
print(f" new_tensor:{x_squeezed}")
print(f"new_shape:{x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1) # h
print(f" new_tensor:{x_unsqueezed}")
print(f"new_shape:{x_unsqueezed.shape}")

 new_tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new_shape:torch.Size([9])
 new_tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new_shape:torch.Size([9, 1])


In [ ]:
#permute:- rearrange the order of the axes value with torch.permute

x_original=torch.rand(size=(224,224,3))

#rearrange the axis order
x_permuted=x_original.permute(2,0,1) #shift axis 0->1,1->2,2->0

print(f"previous shape:{x_original.shape}")
print(f"new shape:{x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
new shape:torch.Size([3, 224, 224])


Indexing(selecting data from tensor)



In [ ]:
#cerate a tensor 
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
#let's inddex bracket by bracket 
print(f"first sqaure bracket :{x[0]}")
print(f"second sqaure braket : {x[0][0]}")
print(f"third sqaure bracket :{x[0][0][0]}")

first sqaure bracket :tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
second sqaure braket : tensor([1, 2, 3])
third sqaure bracket :1


In [ ]:
#get all the value of 0th dimension and the 0 index of 1st dimension

x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#get all the value of the 0th and 1st dim but only index 1 of 2nd dim

x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#get all the value of the 0th  dim but only index 1 of 2nd dim and 1st dim

x[:,1,1]

tensor([5])

In [ ]:
#get all the value of the 2 dim but only index 0 of 0th and 1 st dim

x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#get 9

x[0,2,2]  

tensor(9)

In [ ]:
x[0,:,1]  #x[bracket,row,col]

tensor([2, 5, 8])

**Pytorch tensor and numpy** 


1.NumPyarray  to pytorch tensor

-torch.from_numpy(ndarray)

2.Pytroch tensor ->numpy array

-torch.tensor.numpy()







In [ ]:
#Numpy array to tensor 

import torch 
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor





(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# numpy created wiyh the array with datatype of float64 and if u convert it pytorch tensor
# it keep the same datatype 

#many pytorch calculation default to using float32

# if u want to convert ur float64 to float 32

tensor=torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensor.dtype

torch.float32

NumPy array default datatype is float32
tensor default datatype is float64



In [ ]:
# change the array ,keep the s=tensor same
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

pytorch tensor to numpy

In [ ]:
tensor=torch.ones(7) # create the tensor of ones with dtpe=float32
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor ,keep the array the same

tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility**(take out the random out of random)

randomness is nice and powerful,sometime you'd like there to be little less randomness

so u can peform repeaable expeeriment



In [2]:
import torch

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(f"tensor A:\n{random_tensor_A}\n")
print(f"tensor_B:\n{random_tensor_B}\n")
print("does tensor A equal tensor B?(anywhere)")
random_tensor_A==random_tensor_B


tensor A:
tensor([[0.9724, 0.1989, 0.1894, 0.4666],
        [0.1433, 0.8272, 0.9675, 0.4505],
        [0.0801, 0.5101, 0.3120, 0.2011]])

tensor_B:
tensor([[0.4332, 0.5003, 0.5179, 0.3655],
        [0.6646, 0.9492, 0.4871, 0.1064],
        [0.0233, 0.7743, 0.8275, 0.9640]])

does tensor A equal tensor B?(anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

tensor would still contain random value but they would be of the same value

In [4]:
import torch
import random

#set the random seed 
RANDOM_SEED=42#try change this to different value and see what happens to the number happens
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

#have reset the seed every time a new rand() is calling
#without this  ,tensor_d  would be different to tensor_c

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(f"tensor_c:\n{random_tensor_C}\n")
print(f"tensor_D:\n{random_tensor_D}\n")

random_tensor_C==random_tensor_D



tensor_c:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor_D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])



tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Running the tenosr on gpu**

1.use google colab gpu

2.ur own gpu

3.cloud computuing





In [1]:
!nvidia-smi

Tue Oct  4 06:37:16 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

if u have gpu accessiable above is somthing as output

**2.  Getting the pytorch to run on GPU**

In [2]:
#check for the gpu

import torch
torch.cuda.is_available()


True

In [3]:
#set device type 

device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

it is th best practice  to write device agnostic code this means code that run  on cpu(always availabe) or gpu(is available)

In [4]:
# Count number of devices

torch.cuda.device_count()


1

**putting tensor (and model) on GPU**


In [9]:
 #create tensor (default on cpu)

tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

 # tensor not on gpu

print(tensor,tensor.device)

 # move tensor to gpu(if available)

tensor_on_gpu =tensor.to(device)

tensor_on_gpu


tensor([1, 2, 3]) cpu
tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

device='cuda:0' this means its stored on the 0th gpu availabe  respectively up to'cuda:n'

** Moving the tensor back to the cpu **

In [11]:
# if tensor is on GPU ,cant transfrom it to numpy(this will error)

#tensor_on_gpu.numpy()




In [14]:
#instead ,copy the tensor back to cpu

tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [15]:
# above return a copy of the gpu tensor in cpu memory so the original tensor is still on gpu


In [16]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')